# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deepspeech.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='deepspeech.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\032io.github.keenon.voicecodeB\017DeepSpeechProtoP\001\370\001\001'),
  serialized_pb=_b('\n\x10\x64\x65\x65pspeech.proto\"\t\n\x07Request\"5\n\x0fStreamingResult\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x14\n\x0cintermediate\x18\x02 \x01(\x08\x32<\n\nDeepSpeech\x12.\n\x0cSpeechStream\x12\x08.Request\x1a\x10.StreamingResult\"\x00\x30\x01\x42\x32\n\x1aio.github.keenon.voicecodeB\x0f\x44\x65\x65pSpeechProtoP\x01\xf8\x01\x01\x62\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=29,
)


_STREAMINGRESULT = _descriptor.Descriptor(
  name='StreamingResult',
  full_name='StreamingResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='StreamingResult.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='intermediate', full_name='StreamingResult.intermediate', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['StreamingResult'] = _STREAMINGRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'deepspeech_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  ))
_sym_db.RegisterMessage(Request)

StreamingResult = _reflection.GeneratedProtocolMessageType('StreamingResult', (_message.Message,), dict(
  DESCRIPTOR = _STREAMINGRESULT,
  __module__ = 'deepspeech_pb2'
  # @@protoc_insertion_point(class_scope:StreamingResult)
  ))
_sym_db.RegisterMessage(StreamingResult)


DESCRIPTOR._options = None

_DEEPSPEECH = _descriptor.ServiceDescriptor(
  name='DeepSpeech',
  full_name='DeepSpeech',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=86,
  serialized_end=146,
  methods=[
  _descriptor.MethodDescriptor(
    name='SpeechStream',
    full_name='DeepSpeech.SpeechStream',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_STREAMINGRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEEPSPEECH)

DESCRIPTOR.services_by_name['DeepSpeech'] = _DEEPSPEECH

# @@protoc_insertion_point(module_scope)
